name: HS-API-Tests

on: push

jobs:
  unit-tests:
    name: HS API Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependecies
        run: npm ci

      - name: Run test
        run: ./node_modules/.bin/jest